import os

from azure.ai.projects import AIProjectClient
from azure.identity import DefaultAzureCredential
from dotenv import load_dotenv


def main():
    # ---------------------------------------------------------
    # Clear console
    # ---------------------------------------------------------
    os.system("cls" if os.name == "nt" else "clear")

    # ---------------------------------------------------------
    # Load environment variables
    # ---------------------------------------------------------
    load_dotenv()

    project_endpoint = os.getenv("PROJECT_ENDPOINT")
    agent_name = os.getenv("SPEECH_AGENT_NAME")

    if not project_endpoint:
        raise ValueError("PROJECT_ENDPOINT is not set in .env")

    if not agent_name:
        raise ValueError("SPEECH_AGENT_NAME is not set in .env")

    # ---------------------------------------------------------
    # Connect to our Microsoft Foundry project
    # ---------------------------------------------------------
    project_client = AIProjectClient(
        endpoint=project_endpoint,
        credential=DefaultAzureCredential(),
    )

    # ---------------------------------------------------------
    # Get an OpenAI client connected to our EXISTING
    # ai103-speech-agent.
    #
    # Important:
    # The Speech MCP tool is already configured on the agent
    # in Microsoft Foundry.
    # ---------------------------------------------------------
    openai_client = project_client.get_openai_client(
        agent_name=agent_name
    )

    print(f"Connected to agent: {agent_name}")

    # ---------------------------------------------------------
    # Ask the agent to perform Text-to-Speech.
    #
    # Notice:
    # We do NOT call SpeechSynthesizer here.
    # We give the agent a goal and the agent should select
    # the appropriate Azure Speech MCP tool.
    # ---------------------------------------------------------
    user_prompt = """
    Convert the following text to speech using the available
    Azure Speech tools:

    Hello Pramod. This audio was generated by the Azure Speech
    MCP Server through a Microsoft Foundry agent.

    Return the generated audio result or location.
    """

    response = openai_client.responses.create(
        input=user_prompt
    )

    # ---------------------------------------------------------
    # Display the agent's final response
    # ---------------------------------------------------------
    print("\nAgent response:")
    print(response.output_text)


if __name__ == "__main__":
    main()